# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnse2ATMbXC4aDldn7fKhgKyR0tNq6S5
"""



import pandas as pd
df=pd.DataFrame({'Ism': ['Alijon','Nurulloh','Boynazar','Muxsinjon','Asrorbek','Shohijaxon'],
                 'Familiya':['Boymirzayev','Aminjonov','Toxtasinov','Yusupov','Ubaydulayev','Jaloliddinov'],
                 'Yoshi':['19','19','18','19','19','19'],
                 'Kursi':['2','2','2','2','2','2'],
})
print(df)

df.to_excel('Guruh nomi.xlsx',index=False,sheet_name='Sheet1')